FROM node:18.16.0-slim
ENV NODE_ENV development
WORKDIR /usr/src/app

COPY --chown=node:node tsconfig.json ./
COPY --chown=node:node .env* ./

ENV PNPM_HOME="/root/.local/share/pnpm"
ENV PATH="${PATH}:${PNPM_HOME}"

RUN npm install -g pnpm

COPY package.json ./
COPY pnpm-lock.yaml ./

RUN pnpm fetch
RUN pnpm install -r --offline

USER node

CMD ["pnpm", "tsx", "watch", "--clear-screen=false", "src/index.ts"]